require "symbols-outline".setup {
  -- highlight_hovered_item = false,
  fold_markers = { '▶', '▽' },
  width = 35,
  symbols = {
    File = { icon = "File", hl = "TSURI" },
    Module = { icon = "Mod", hl = "TSNamespace" },
    Namespace = { icon = "Name", hl = "TSNamespace" },
    Package = { icon = "Pack", hl = "TSNamespace" },
    Class = { icon = "Class", hl = "SymTSType" },
    Method = { icon = "ƒ", hl = "SymTSMethod" },
    Property = { icon = "Property", hl = "SymTSField" },
    Field = { icon = "Field", hl = "SymTSField" },
    Constructor = { icon = "Constructor", hl = "TSConstructor" },
    Enum = { icon = "Enum", hl = "SymTSType" },
    Interface = { icon = "Interface", hl = "SymInterface" },
    Function = { icon = "Fn", hl = "SymTSFunction" },
    Variable = { icon = "Var", hl = "TSConstant" },
    Constant = { icon = "Const", hl = "TSConstant" },
    String = { icon = "String", hl = "TSString" },
    Number = { icon = "#", hl = "TSNumber" },
    Boolean = { icon = "Bool", hl = "TSBoolean" },
    Array = { icon = "[]", hl = "TSConstant" },
    Object = { icon = "Obj", hl = "SymObj" },
    Key = { icon = "Key", hl = "SymTSType" },
    Null = { icon = "NULL", hl = "SymTSType" },
    EnumMember = { icon = "Variant", hl = "SymTSField" },
    Struct = { icon = "Struct", hl = "SymTSType" },
    Event = { icon = "Event", hl = "SymTSType" },
    Operator = { icon = "Op", hl = "TSOperator" },
    TypeParameter = { icon = "T", hl = "TSParameter" }
  },
  keymaps = { -- These keymaps can be a string or a table for multiple keys
    close = { "<Esc>", "q" },
    goto_location = "<Cr>",
    focus_location = "o",
    hover_symbol = "h",
    toggle_preview = "l",
    rename_symbol = "r",
    code_actions = "a",
    fold = { "w", "zm" },
    unfold = { "e", "zr" },
    fold_all = { "W", "zM" },
    unfold_all = { "E", "zR" },
    fold_reset = "R",
  },
}
